[package]
name = "rustodon"
version = "0.1.0"
authors = ["The Rustodon team"]

[workspace]
members = ['database/', 'lib/resopt/', 'lib/posticle/']

[dependencies]
chrono = "0.4"
dotenv = "0.10"
failure = "0.1.1"
failure_derive = "0.1.1"
lazy_static = "1.0"
itertools = "0.7.4"
resopt = { path = "lib/resopt/" }

rocket = "0.3.10"
rocket_codegen = "0.3.10"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.6.3"
validator_derive = "0.6.5"

[dependencies.rustodon_database]
path = "database/"

[dependencies.rocket_contrib]
version = "0.3.8"
default-features = false
features = ["json"]

[dependencies.maud]
version = "0.17.4"
features = ["rocket"]
