[package]
name = "rustodon"
version = "0.1.0"
authors = ["The Rustodon team"]
edition = "2018"

[workspace]
members = ['database/', 'lib/resopt/', 'lib/posticle/']

[dependencies]
chrono = "0.4"
dotenv = "0.13"
maplit = "1.0"
failure = "0.1.4"
failure_derive = "0.1.4"
lazy_static = "1.2"
itertools = "0.8.0"
resopt = { path = "lib/resopt/" }
posticle = { path = "lib/posticle/" }
regex = "1.1.0"

slog = "2.4"
slog-term = "2.4"
slog-async = "2.3"
slog-scope = "4.0"
rocket-slog = "0.4"

rocket = "0.4"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.8"
validator_derive = "0.8"

ammonia = "2.0.0"

diesel = { version = "1.3.3", features = ["postgres", "chrono", "r2d2"] }

[dependencies.db]
path = "database/"
package = "rustodon_database"

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json"]

[dependencies.askama]
git = "https://github.com/djc/askama"
rev = "5549f9a"
features = ["with-rocket"]

[build-dependencies.askama]
git = "https://github.com/djc/askama"
rev = "5549f9a"
features = ["with-rocket"]
