[package]
name = "rustodon"
version = "0.1.0"
authors = ["The Rustodon team"]

[workspace]
members = ['database/', 'lib/resopt/', 'lib/posticle/']

[dependencies]
chrono = "0.4"
dotenv = "0.13"
maplit = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
lazy_static = "1.0"
itertools = "0.7.4"
resopt = { path = "lib/resopt/" }
posticle = { path = "lib/posticle/" }
turnstile = { path = "lib/turnstile/" }
regex = "1.0.0"

rocket = "0.3.15"
rocket_codegen = "0.3.15"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.7"
validator_derive = "0.7"

ammonia = "1.1.0"
maud_htmlescape = "0.17.0"

diesel = { version = "1.3.2", features = ["postgres", "chrono", "serde_json", "r2d2"] }

[dependencies.rustodon_database]
path = "database/"

[dependencies.rocket_contrib]
version = "0.3.8"
default-features = false
features = ["json"]

[dependencies.askama]
version = "0.7.0"
features = ["with-rocket"]

[build-dependencies.askama]
version = "0.7.0"
features = ["with-rocket"]
